[versions]
junit = "5.10.1"
jackson-databind = "2.15.2"
maven-publish-plugin = "0.28.0"

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-plugin" }

[bundles]
test = ["junit-jupiter", "jackson-databind"]
